#!/bin/sh

. /mod/etc/conf/mosquitto.cfg

cat << EOF
user nobody
pid_file /var/run/mosquitto/mosquitto.pid
listener $MOSQUITTO_PORT
EOF

[ "$MOSQUITTO_ALLOW_ANONYMOUS" = "yes" ] && echo "allow_anonymous true"

if [ -n "$MOSQUITTO_PERSISTENCE_PATH" ]; then
	echo "persistence true" && echo "persistence_location $MOSQUITTO_PERSISTENCE_PATH"
else
	echo "persistence false"
fi

[ "$MOSQUITTO_SYSLOG" = "yes" ] && echo "log_dest syslog"

