$(call PKG_INIT_BIN, $(if $(FREETZ_PACKAGE_GNU_MAKE_VERSION_ABANDON),4.2.1,4.4.1))
$(PKG)_SOURCE:=make-$($(PKG)_VERSION).tar.$(if $(FREETZ_PACKAGE_GNU_MAKE_VERSION_ABANDON),bz2,gz)
$(PKG)_HASH_ABANDON:=d6e262bf3601b42d2b1e4ef8310029e1dcf20083c5446b4b7aa67081fdffc589
$(PKG)_HASH_CURRENT:=dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3
$(PKG)_HASH:=$($(PKG)_HASH_$(if $(FREETZ_PACKAGE_GNU_MAKE_VERSION_ABANDON),ABANDON,CURRENT))
$(PKG)_SITE:=@GNU/make

$(PKG)_CATEGORY:=M

$(PKG)_BINARY:=$($(PKG)_DIR)/make
$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/make

$(PKG)_CONDITIONAL_PATCHES+=$(if $(FREETZ_PACKAGE_GNU_MAKE_VERSION_ABANDON),abandon,current)

$(PKG)_CONFIGURE_ENV += ac_cv_lib_elf_elf_begin=no
$(PKG)_CONFIGURE_ENV += make_cv_sys_gnu_glob=no
$(PKG)_CONFIGURE_ENV += GLOBINC='-Iglob/'
$(PKG)_CONFIGURE_ENV += GLOBLIB=glob/libglob.a


ifneq ($($(PKG)_SOURCE),$(MAKE_HOST_SOURCE))
$(PKG_SOURCE_DOWNLOAD)
endif
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CONFIGURE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(GNU_MAKE_DIR)

$($(PKG)_TARGET_BINARY): $($(PKG)_BINARY)
	$(INSTALL_BINARY_STRIP)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)


$(pkg)-clean:
	-$(SUBMAKE) -C $(GNU_MAKE_DIR) clean

$(pkg)-uninstall:
	$(RM) $(GNU_MAKE_TARGET_BINARY)

$(PKG_FINISH)
