#! /usr/bin/env bash
# generates docs/host-tools/README.md
MDPWD="$(dirname $(realpath $0))"
INPWD="$MDPWD/../../make/host-tools"

echo '[//]: # ( Do not edit this file! Run generate.sh to create it. )' > "$MDPWD/README.md"
echo "# Host-Tools" >> "$MDPWD/README.md"
( CTN="Index: " && for x in $(echo {A..Z}); do CTN="$CTN[$x](#${x,,}) - "; done && echo ${CTN:0:-3} ) >> "$MDPWD/README.md"

for dir in $(find "$INPWD" -maxdepth 1 -mindepth 1 -type d | sort); do
	tool="${dir##*/}"
	[ "${tool:0:1}" != "$IDX" ] && IDX="${tool:0:1}" && echo -e "\n### ${IDX^^}"

	ver="$(sed -rn "s/^### VERSION:= *(.*)/ \1/p" $dir/*.mk 2>/dev/null)"
	[ -z "$ver" ] && ver="$(sed -n 's/^\$(call TOOLS_INIT, *v*\(.*\))/ \1/p' $dir/*.mk 2>/dev/null)"
	dsc="${tool%-host}"
	itm="$dsc$ver"
	anc="${tool//_/-}"
	echo -e "\n  * **[$itm]($tool.md)<a id='${anc%-cgi}'></a>**<br>"

	touch "$MDPWD/$tool.md"
	while [ "0$(awk 'END{print NR}' "$MDPWD/$tool.md" 2>/dev/null)" -lt 2 ]; do echo >> "$MDPWD/$tool.md"; done
	sed "1c# $itm" -i "$MDPWD/$tool.md"

	sed "/^  - Maintainer: .*$/d" -i "$MDPWD/$tool.md"
	lnk="$(sed -n "s/^### SUPPORT:= *//p" $dir/*.mk)"
	case "$lnk" in
		X)	lnk="" ;;
		"")	lnk="-" ;;
		*)	[ "$lnk" != "${lnk/:\/\//}" ] && lnk="\[$lnk\]($lnk)" || lnk="\[@$lnk\](https://github.com/$lnk)" ;; #"
	esac
	[ -n "$lnk" ] && sed "2i\  - Maintainer: $lnk" -i "$MDPWD/$tool.md"

	lnk="https://github.com/Freetz-NG/freetz-ng/tree/master/make/host-tools/$tool/"
	sed "/^  - Host-Tool: \[.*)$/d" -i "$MDPWD/$tool.md"
	sed "2i\  - Host-Tool: \[${lnk:44}\]($lnk)" -i "$MDPWD/$tool.md"

	for pair in CVSREPO°Repository CHANGES°Changelog MANPAGE°Manpage WEBSITE°Homepage; do
		sed "/^  - ${pair#*°}: \[.*)$/d" -i "$MDPWD/$tool.md"
		lnk="$(sed -n "s/^### ${pair%%°*}:= *//p" $INPWD/$tool/*.mk 2>/dev/null)"
		[ -n "$lnk" ] && sed "2i\  - ${pair#*°}: \[$lnk\]($lnk)" -i "$MDPWD/$tool.md"
	done

done >> "$MDPWD/README.md"

