#! /usr/bin/env bash
MYOWN="$(realpath $0)"
TOOLS="$(dirname $(dirname $MYOWN))"
CAC="$TOOLS/cacert.pem"

[ -s "$CAC" ] && export SSL_CERT_DIR="$CAC"

file="$TOOLS/build/bin/cmake"
[ -x "$file" ] && exec "$file" "$@"

file="$(which -a 'cmake' | grep -v "^$MYOWN$" | head -n1)"
[ -x "$file" ] && exec "$file" "$@"

echo "Miserable failure, no cmake binary!" >&2
exit 1
