#! /usr/bin/env bash
MYOWN="$(realpath $0)"
TOOLS="$(dirname $(dirname $MYOWN))"

CAC="$TOOLS/cacert.pem"
if [ -s "$CAC" ]; then
file="$TOOLS/wget"
[ -x "$file" ] && exec "$file" ${CAC:+--ca-certificate="$CAC"} "$@"
fi

file="$(which -a 'wget' | grep -v "^$MYOWN$" | head -n1)"
[ -x "$file" ] && exec "$file" "$@"

echo "Miserable failure, no wget binary!" >&2
exit 1
