$(call PKG_INIT_BIN, $(if $(FREETZ_PACKAGE_MOSQUITTO_VERSION_ABANDON),2.0.22,2.1.2))
$(PKG)_LIB_VERSION:=1
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH_ABANDON:=2f752589ef7db40260b633fbdb536e9a04b446a315138d64a7ff3c14e2de6b68
$(PKG)_HASH_CURRENT:=fd905380691ac65ea5a93779e8214941829e3d6e038d5edff9eac5fd74cbed02
$(PKG)_HASH:=$($(PKG)_HASH_$(if $(FREETZ_PACKAGE_MOSQUITTO_VERSION_ABANDON),ABANDON,CURRENT))
$(PKG)_SITE:=https://mosquitto.org/files/source,https://ftp.fau.de/gentoo/distfiles/95
### WEBSITE:=https://www.mosquitto.org/
### MANPAGE:=https://www.mosquitto.org/documentation/
### CHANGES:=https://mosquitto.org/blog/
### CVSREPO:=https://github.com/eclipse/mosquitto
### STEWARD:=pfichtner

$(PKG)_BINARY_BROKER:=$($(PKG)_DIR)/src/mosquitto
$(PKG)_BINARY_MOSQUITTO_PASSWD:=$($(PKG)_DIR)/apps/mosquitto_passwd/mosquitto_passwd
$(PKG)_BINARY_CLIENT_PUB:=$($(PKG)_DIR)/client/mosquitto_pub
$(PKG)_BINARY_CLIENT_SUB:=$($(PKG)_DIR)/client/mosquitto_sub
$(PKG)_BINARY_CLIENT_RR:=$($(PKG)_DIR)/client/mosquitto_rr

$(PKG)_TARGET_BINARY_BROKER:=$($(PKG)_DEST_DIR)/usr/bin/mosquitto
$(PKG)_TARGET_BINARY_MOSQUITTO_PASSWD:=$($(PKG)_DEST_DIR)/usr/bin/mosquitto_passwd
$(PKG)_TARGET_BINARY_CLIENT_PUB:=$($(PKG)_DEST_DIR)/usr/bin/mosquitto_pub
$(PKG)_TARGET_BINARY_CLIENT_SUB:=$($(PKG)_DEST_DIR)/usr/bin/mosquitto_sub
$(PKG)_TARGET_BINARY_CLIENT_RR:=$($(PKG)_DEST_DIR)/usr/bin/mosquitto_rr

$(PKG)_LIBNAME:=lib$(pkg).so.$($(PKG)_LIB_VERSION)
$(PKG)_LIB_BINARY:=$($(PKG)_DIR)/lib/$($(PKG)_LIBNAME)
$(PKG)_LIB_TARGET_BINARY:=$($(PKG)_DEST_LIBDIR)/$($(PKG)_LIBNAME)

$(PKG)_EXCLUDED += $(if $(FREETZ_PACKAGE_MOSQUITTO_BROKER),,usr/bin/mosquitto etc/default.mosquitto/mosquitto.cfg etc/default.mosquitto/mosquitto_conf etc/default.mosquitto/mosquitto_extra.def etc/init.d/rc.mosquitto usr/lib/cgi-bin/mosquitto.cgi)
$(PKG)_EXCLUDED += $(if $(FREETZ_PACKAGE_MOSQUITTO_PASSWD),,usr/bin/mosquitto_passwd)
$(PKG)_EXCLUDED += $(if $(FREETZ_PACKAGE_MOSQUITTO_CLIENT_PUB),,usr/bin/mosquitto_pub)
$(PKG)_EXCLUDED += $(if $(FREETZ_PACKAGE_MOSQUITTO_CLIENT_SUB),,usr/bin/mosquitto_sub)
$(PKG)_EXCLUDED += $(if $(FREETZ_PACKAGE_MOSQUITTO_CLIENT_RR),,usr/bin/mosquitto_rr)
$(PKG)_EXCLUDED += $(if $(FREETZ_PACKAGE_MOSQUITTO_CLIENTS),,$(FREETZ_LIBRARY_DIR)/$($(PKG)_LIBNAME))

$(PKG)_DEPENDS_ON += cmake-host
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MOSQUITTO_VERSION_ABANDON),,libcjson)
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MOSQUITTO_WITH_SSL),openssl)

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MOSQUITTO_VERSION_ABANDON
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MOSQUITTO_WITH_SSL
ifeq ($(strip $(FREETZ_PACKAGE_MOSQUITTO_WITH_SSL)),y)
$(PKG)_REBUILD_SUBOPTS += FREETZ_OPENSSL_SHORT_VERSION
endif

$(PKG)_CONDITIONAL_PATCHES+=$(if $(FREETZ_PACKAGE_MOSQUITTO_VERSION_ABANDON),abandon,current)

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX="/"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_RUNSTATEDIR="/var/run"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DINC_MEMTRACK=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_PLUGINS=On

ifeq ($(strip $(FREETZ_PACKAGE_MOSQUITTO_VERSION_ABANDON)),y)
$(PKG)_CONFIGURE_OPTIONS += -DWITH_CJSON=NO
$(PKG)_CONFIGURE_OPTIONS += -DDOCUMENTATION=NO
else
$(PKG)_CONFIGURE_OPTIONS += -DWITH_DOCS=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_TESTS=NO

$(PKG)_CONFIGURE_OPTIONS += -DWITH_PLUGIN_ACL_FILE=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_PLUGIN_DYNAMIC_SECURITY=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_PLUGIN_EXAMPLES=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_PLUGIN_PASSWORD_FILE=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_PLUGIN_PERSIST_SQLITE=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_PLUGIN_SPARKPLUG_AWARE=NO

$(PKG)_CONFIGURE_OPTIONS += -DARGON2_DIR=""
$(PKG)_CONFIGURE_OPTIONS += -DARGON2_INCLUDE_DIR=""
$(PKG)_CONFIGURE_OPTIONS += -DARGON2_LIBRARY=""
$(PKG)_CONFIGURE_OPTIONS += -DREADLINE_INCLUDE_DIR=""
$(PKG)_CONFIGURE_OPTIONS += -DREADLINE_LIBRARY=""

$(PKG)_CONFIGURE_OPTIONS += -DWITH_CTRL_SHELL=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_LTO=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_WEBSOCKETS_BUILTIN=OFF
endif

$(PKG)_CONFIGURE_OPTIONS += -DWITH_SRV=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_LIB_CPP=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_SOCKS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DWITH_WEBSOCKETS=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_EC=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_TLS_PSK=NO
$(PKG)_CONFIGURE_OPTIONS += -DWITH_TLS=$(if $(FREETZ_PACKAGE_MOSQUITTO_WITH_SSL),YES,NO)


$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY_BROKER) $($(PKG)_BINARY_MOSQUITTO_PASSWD) $($(PKG)_BINARY_CLIENT_PUB) $($(PKG)_BINARY_CLIENT_SUB) $($(PKG)_BINARY_CLIENT_RR) $($(PKG)_LIB_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(MOSQUITTO_DIR)
#cmake	cd $(MOSQUITTO_DIR) && cmake -LA .

$($(PKG)_TARGET_BINARY_BROKER): $($(PKG)_BINARY_BROKER)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_TARGET_BINARY_MOSQUITTO_PASSWD): $($(PKG)_BINARY_MOSQUITTO_PASSWD)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_TARGET_BINARY_CLIENT_PUB): $($(PKG)_BINARY_CLIENT_PUB)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_TARGET_BINARY_CLIENT_SUB): $($(PKG)_BINARY_CLIENT_SUB)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_TARGET_BINARY_CLIENT_RR): $($(PKG)_BINARY_CLIENT_RR)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_LIB_TARGET_BINARY): $($(PKG)_LIB_BINARY)
	$(INSTALL_LIBRARY_STRIP)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY_BROKER) $(if $(FREETZ_PACKAGE_MOSQUITTO_PASSWD),$($(PKG)_TARGET_BINARY_MOSQUITTO_PASSWD)) $($(PKG)_TARGET_BINARY_CLIENT_PUB) $($(PKG)_TARGET_BINARY_CLIENT_SUB) $($(PKG)_TARGET_BINARY_CLIENT_RR) $($(PKG)_LIB_TARGET_BINARY)


$(pkg)-clean:
	-$(SUBMAKE) -C $(MOSQUITTO_DIR) clean
	$(RM) $(MOSQUITTO_DIR)/.configured

$(pkg)-uninstall:
	$(RM) \
	  $(MOSQUITTO_TARGET_BINARY_BROKER) \
	  $(MOSQUITTO_TARGET_BINARY_MOSQUITTO_PASSWD) \
	  $(MOSQUITTO_TARGET_BINARY_CLIENT_PUB) \
	  $(MOSQUITTO_TARGET_BINARY_CLIENT_SUB) \
	  $(MOSQUITTO_TARGET_BINARY_CLIENT_RR) \
	  $(MOSQUITTO_LIB_TARGET_BINARY)

$(PKG_FINISH)
