#!/bin/sh

#
# Architecture / endianness specific values
#

# Machine
ac_cv_c_littleendian=yes
ac_cv_c_bigendian=no

# Types and sizes
ac_cv_sizeof_fpos_t=24

# Common values for 32bit architectures
. $FREETZ_BASE_DIR/include/config.site/_common-linux-uclibc32

# Common values for all architectures
. $FREETZ_BASE_DIR/include/config.site/_common-linux-uclibc

