$(call PKG_INIT_BIN, $(if $(FREETZ_PACKAGE_MINISATIP_VERSION_ABANDON),1.0.4,v1.3.6))
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.xz
$(PKG)_HASH_ABANDON:=a057675594af78c2ac1be1c0377e009bd6d21762ba442b560b675cb93573fbe0
$(PKG)_HASH_CURRENT:=3cff7743e3687c023a2ed0d2ac5f6ff76e3d69c4998460ed1c6ec3f3417b56a7
$(PKG)_HASH:=$($(PKG)_HASH_$(if $(FREETZ_PACKAGE_MINISATIP_VERSION_ABANDON),ABANDON,CURRENT))
$(PKG)_SITE:=git@https://github.com/catalinii/minisatip
### WEBSITE:=https://minisatip.org
### MANPAGE:=https://github.com/catalinii/minisatip/wiki
### CHANGES:=https://github.com/catalinii/minisatip/releases
### CVSREPO:=https://github.com/catalinii/minisatip

$(PKG)_BINARY:=$($(PKG)_DIR)/$(pkg)
$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/$(pkg)

$(PKG)_WEBROOT := $($(PKG)_DIR)/html
$(PKG)_TARGET_WEBROOT := $($(PKG)_DEST_DIR)/usr/share/minisatip/html

$(PKG)_EXCLUDED += $(if $(FREETZ_PACKAGE_MINISATIP_HTML),,usr/share)

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MINISATIP_VERSION_ABANDON
$(PKG)_CONDITIONAL_PATCHES+=$(if $(FREETZ_PACKAGE_MINISATIP_VERSION_ABANDON),abandon,current)
$(PKG)_CONDITIONAL_PATCHES+=$(if $(FREETZ_KERNEL_VERSION_2_6_39_MAX),$(if $(FREETZ_KERNEL_VERSION_2_6_39_4),,abandon/sendmmsg))

$(PKG)_CONFIGURE_OPTIONS += --disable-netcv
$(PKG)_CONFIGURE_OPTIONS += --disable-axe
ifeq ($(strip $(FREETZ_PACKAGE_MINISATIP_VERSION_ABANDON)),y)
$(PKG)_CONFIGURE_OPTIONS += --disable-enigma
else
$(PKG)_CONFIGURE_OPTIONS += --disable-static
$(PKG)_CONFIGURE_OPTIONS += --without-xml2
endif

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MINISATIP_LINUXDVB
$(PKG)_CONFIGURE_OPTIONS += --$(if $(FREETZ_PACKAGE_MINISATIP_LINUXDVB),enable,disable)-linuxdvb

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MINISATIP_SATIPC
$(PKG)_CONFIGURE_OPTIONS += --$(if $(FREETZ_PACKAGE_MINISATIP_SATIPC),enable,disable)-satipc

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MINISATIP_DVBAPI
$(PKG)_CONFIGURE_OPTIONS += --$(if $(FREETZ_PACKAGE_MINISATIP_DVBAPI),enable,disable)-dvbapi

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MINISATIP_DVBCA
$(PKG)_CONFIGURE_OPTIONS += --$(if $(FREETZ_PACKAGE_MINISATIP_DVBCA),enable,disable)-dvbca
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MINISATIP_DVBCA),openssl)

ifeq ($(strip $(FREETZ_PACKAGE_MINISATIP_VERSION_ABANDON)),y)
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MINISATIP_DVBAES
$(PKG)_CONFIGURE_OPTIONS += --$(if $(FREETZ_PACKAGE_MINISATIP_DVBAES),enable,disable)-dvbaes
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MINISATIP_DVBAES),openssl)
endif

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MINISATIP_DVBCSA
$(PKG)_CONFIGURE_OPTIONS += --$(if $(FREETZ_PACKAGE_MINISATIP_DVBCSA),enable,disable)-dvbcsa
$(PKG)_DEPENDS_ON += $(if $(FREETZ_PACKAGE_MINISATIP_DVBCSA),libdvbcsa)

$(PKG)_CONFIGURE_ENV += ac_cv_func_backtrace=no


$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CONFIGURE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(MINISATIP_DIR)

$($(PKG)_TARGET_BINARY): $($(PKG)_BINARY)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_TARGET_WEBROOT): $($(PKG)_WEBROOT)
	$(INSTALL_DIR)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY) $($(PKG)_TARGET_WEBROOT)


$(pkg)-clean:
	-$(SUBMAKE) -C $(MINISATIP_DIR) clean
	$(RM) $(MINISATIP_DIR)/.configured

$(pkg)-uninstall:
	$(RM) $(MINISATIP_TARGET_BINARY)
	$(RM) -r $(MINISATIP_TARGET_WEBROOT)

$(PKG_FINISH)
