$(call TOOLS_INIT, 3.0.15)
$(PKG)_SOURCE:=$(pkg_short)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=23c666d0edf20f14249b3d8f0368acaee9ab585b09e1de82107c66e1f3ec9533
$(PKG)_SITE:=https://www.openssl.org/source,https://github.com/openssl/openssl/releases/download/openssl-$($(PKG)_VERSION)
### WEBSITE:=https://www.openssl.org/source/
### MANPAGE:=https://www.openssl.org/docs/
### CHANGES:=https://www.openssl.org/news/changelog.html
### CVSREPO:=https://github.com/openssl/openssl
### SUPPORT:=fda77

$(PKG)_DEPENDS_ON+=patchelf-host

$(PKG)_DESTDIR            := $(FREETZ_BASE_DIR)/$(TOOLS_BUILD_DIR)/lib
$(PKG)_INSTALLDIR         := $(OPENSSL_HOST_DIR)/installdir

# Makefile is regenerated by configure
$(PKG)_PATCH_POST_CMDS += $(RM) Makefile Makefile.bak;
$(PKG)_PATCH_POST_CMDS += ln -s Configure configure;

$(PKG)_CONFIGURE_OPTIONS += --prefix=$(OPENSSL_HOST_INSTALLDIR)


$(TOOLS_SOURCE_DOWNLOAD)
$(TOOLS_UNPACKED)
$(TOOLS_CONFIGURED_CONFIGURE)

$($(PKG)_DIR)/.compiled: $($(PKG)_DIR)/.configured
	$(TOOLS_SUBMAKE) -C $(OPENSSL_HOST_DIR) all
	@touch $@

$($(PKG)_DIR)/.installed: $($(PKG)_DIR)/.compiled
	$(TOOLS_SUBMAKE) -C $(OPENSSL_HOST_DIR) install_sw
	@mkdir -p $(OPENSSL_HOST_DESTDIR)/
	cp -a $(OPENSSL_HOST_DIR)/{libcrypto,libssl}.so.3 $(OPENSSL_HOST_DESTDIR)/
	$(call OPENSSL_HOST_FIXHARDCODED)
	@touch $@

define $(PKG)_FIXHARDCODED
	@$(PATCHELF) --replace-needed libcrypto.so.3 $(OPENSSL_HOST_DESTDIR)/libcrypto.so.3 $(OPENSSL_HOST_DESTDIR)/libssl.so.3
endef

$(pkg)-fixhardcoded:
	$(call OPENSSL_HOST_FIXHARDCODED)

$(pkg)-precompiled: $($(PKG)_DIR)/.installed


$(pkg)-clean:
	-$(MAKE) -C $(OPENSSL_HOST_DIR) clean
	$(RM) $(OPENSSL_HOST_DIR)/.{configured,compiled,installed,fixhardcoded}

$(pkg)-dirclean:
	$(RM) -r $(OPENSSL_HOST_DIR)

$(pkg)-distclean: $(pkg)-dirclean
	$(RM) $(OPENSSL_HOST_DESTDIR)/{libcrypto,libssl}.so.3

$(TOOLS_FINISH)
