name: github_docker

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/github_docker.yml'
      - '.github/docker/*/*'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/docker/*/*'
  schedule:
    - cron: '45 18 28 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}${{ github.event.pull_request.number && '-' }}${{ github.event.pull_request.number || '' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' && false || true }}


jobs:
  matrizifizieren:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-24.04
    if: github.repository == 'freetz-ng/freetz-ng' || github.event_name == 'workflow_dispatch'

    outputs:
      gitsha: ${{ steps.parse.outputs.gitsha }}
      matrix: ${{ steps.parse.outputs.matrix }}

    steps:

      - name: checkout
        uses: actions/checkout@v6

      - name: parse
        id: parse
        run: |
          echo "gitsha=\"${{ github.sha }}\"" >> $GITHUB_OUTPUT
          find .github/docker/ -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | \
          while read -r line; do \
            echo -n "$matrix\"$line\","; \
          done | sed 's/^/matrix=\[/;s/,$/\]/' >> $GITHUB_OUTPUT

      - name: vars
        id: vars
        run: |
          echo "################################################################"
          echo "gitsha=${{ steps.parse.outputs.gitsha }}"
          echo "matrix=${{ steps.parse.outputs.matrix }}"

  build:
    permissions:
      contents: read
      packages: write
    needs: matrizifizieren
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.matrizifizieren.outputs.matrix) }}
    runs-on: ubuntu-24.04

    steps:

      - name: checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ fromJson(needs.matrizifizieren.outputs.gitsha) }}

      - name: login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.FREETZ_DLTOKEN || secrets.GITHUB_TOKEN }}
        if: github.repository == 'freetz-ng/freetz-ng' && github.event_name != 'pull_request'

      - name: docker
        uses: docker/build-push-action@v7
        with:
          context: .github/docker/${{ matrix.image }}
          tags: ghcr.io/freetz-ng/internal/${{ matrix.image }}:latest
          push: ${{ github.repository == 'freetz-ng/freetz-ng' && github.event_name != 'pull_request' }}


