name: github_ghpages

on:
# workflow_run:
#   workflows: [ postcommit_docs,postcommit_stats,avm_ftp,avm_osp,avm_juis,avm_juis-recache ]
#   types:
#     - completed
# push:
#   branches: [ master ]
#   paths:
#     - '.github/workflows/github_ghpages.yml'
#     - 'docs/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    if: ${{ github.repository == 'freetz-ng/freetz-ng' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-slim
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5


